// app/layout.tsx
import './globals.css'
import { Inter } from 'next/font/google'
import type { Metadata } from 'next'
import { Providers } from './providers' // ✅ Import dari langkah sebelumnya

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Event Organizer App',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers> {/* ✅ Gunakan Providers di sini */}
          {children}
        </Providers>
      </body>
    </html>
  )
}
