import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import AuthButton from '@/components/AuthButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Event Organizer App',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header className="p-4 bg-gray-800 text-white">
            <AuthButton /> {/* Tampilkan tombol login/logout */}
          </header>
          {children}
        </Providers>
      </body>
    </html>
  )
}
